# Generated by Django 5.0.3 on 2024-04-09 11:35

import cloudinary.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarshippage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipindexpage',
            name='academic_charge',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write a short inspiring educational message', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipindexpage',
            name='church_invitation_body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write a short invitation message', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipindexpage',
            name='church_invitation_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipindexpage',
            name='banner',
            field=cloudinary.models.CloudinaryField(help_text='Select a background banner image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
