# Generated by Django 5.0.3 on 2024-04-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_scholarshippage_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarshippage',
            options={'ordering': ['-date_created']},
        ),
    ]
