# Generated by Django 5.0.3 on 2024-04-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceIndexPage',
            new_name='BookIndexPage',
        ),
    ]
