# Generated by Django 5.0.3 on 2024-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='short_highlight',
            field=models.CharField(blank=True, help_text='Write a very short highlight of the post to captivate readers', max_length=1000, null=True),
        ),
    ]
