# Generated by Django 5.0.3 on 2024-04-24 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='page',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='submit_time',
        ),
    ]
