# Generated by Django 5.0.3 on 2024-05-04 14:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_eventregistration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='cashapp_number',
            new_name='donate_account_name',
        ),
        migrations.RenameField(
            model_name='donate',
            old_name='cashapp_tag',
            new_name='donate_account_number',
        ),
        migrations.AddField(
            model_name='donate',
            name='donate_account_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for the donate account', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='donate',
            name='donate_account_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
