# Generated by Django 5.0.3 on 2024-04-01 14:48

import cloudinary.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_iamnew_first_section_body_iamnew_first_section_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=500, null=True)),
                ('short_description', wagtail.fields.RichTextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_start_time', models.TimeField(blank=True, null=True)),
                ('event_end_time', models.TimeField(blank=True, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=500, null=True)),
                ('event_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('can_register', models.BooleanField(default=False)),
                ('external_registration', models.BooleanField(default=False)),
                ('external_registration_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='worshipservice',
            old_name='time_from',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_church_background_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_church_image_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_church_text_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_church_title_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image_4',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='slider_image_5',
        ),
        migrations.RemoveField(
            model_name='worshipservice',
            name='time_to',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_church_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_church_image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='worshipservice',
            name='service_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=500, null=True),
        ),
    ]
