# Generated by Django 5.0.3 on 2024-04-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_event_display_on_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='worshipservice',
            name='service_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
