# Generated by Django 5.0.3 on 2024-04-06 13:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_worshipservice_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='church_address',
            field=models.CharField(blank=True, help_text='Enter the church address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='church_description1',
            field=models.CharField(blank=True, help_text='Enter a very short inspiring message here', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='church_description2',
            field=models.CharField(blank=True, help_text='Enter a very short inspiring message here', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='church_google_map_embed_iframe',
            field=models.URLField(blank=True, help_text='Enter the church location google map iframe embed src link', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='church_name',
            field=models.CharField(blank=True, help_text='Enter the name of the church e.g DLCF Nashville', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='donate_background_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select image to use as donate background image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='donate_main_subtext',
            field=models.CharField(blank=True, help_text='make text as short as possible', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='donate_main_text',
            field=models.CharField(blank=True, help_text='make text as short as possible', max_length=500, null=True),
        ),
    ]
