# Generated by Django 5.0.3 on 2024-04-06 13:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_church_address_homepage_church_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='church_location_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select image of church location', max_length=255, null=True, verbose_name='image'),
        ),
    ]
