# Generated by Django 5.0.3 on 2024-04-06 14:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_church_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='connect_with_us_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select image for connect with us background image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='connect_with_us_sub_text',
            field=models.CharField(blank=True, help_text='Enter a very short inspiring message here', max_length=500, null=True),
        ),
    ]
