# Generated by Django 5.0.3 on 2024-04-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_connect_with_us_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
