# Generated by Django 5.0.3 on 2024-04-06 17:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_event_date_event_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='GS_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select image of the General Superintendent', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='ministries_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Ministry image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='our_belief_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Our believe image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='who_we_are_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Who we are image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
