# Generated by Django 5.0.3 on 2024-04-06 17:55

import cloudinary.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_about_gs_image_about_ministries_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='location_church_image1',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Location church image 1', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='location_church_image2',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Location church image 2', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='location_church_image3',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Location church image 3', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='about',
            name='message_from_location_church_heading',
            field=models.CharField(blank=True, help_text='Write a short inspiring heading', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='message_from_location_church_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write a short inspiring message here', null=True),
        ),
    ]
