# Generated by Django 5.0.3 on 2024-04-06 18:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_about_location_church_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='message_from_location_church_text2',
            field=wagtail.fields.RichTextField(blank=True, help_text='Write a short inspiring message here', null=True),
        ),
    ]
