# Generated by Django 5.0.3 on 2024-04-06 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_about_message_from_location_church_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='ministries',
        ),
        migrations.RemoveField(
            model_name='about',
            name='ministries_image',
        ),
        migrations.AddField(
            model_name='about',
            name='advert_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='You can add a unique advertisement banner image here', max_length=255, null=True, verbose_name='image'),
        ),
    ]
