# Generated by Django 5.0.3 on 2024-04-14 15:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_importantpages_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_church_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select the first about us image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_church_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select the second about us image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_church_image_3',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select the third about us image', max_length=255, null=True, verbose_name='image'),
        ),
    ]
