# Generated by Django 5.0.3 on 2024-04-17 10:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_homepage_about_church_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Select the background image for the hero section', max_length=255, null=True, verbose_name='image'),
        ),
    ]
